// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sitemap": {
            "get": {
                "description": "Return sitemap url list. Example of the sitemap url: https://www.shopify.com/sitemap.xml",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sitemap"
                ],
                "summary": "Get the sitemap url list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sitemap.url_scrape"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "sitemap.url_scrape": {
            "type": "object",
            "properties": {
                "changefreq": {
                    "type": "string"
                },
                "lastmod": {
                    "type": "string"
                },
                "loc": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Kubernetes API",
	Description:      "List of kubernetes API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
