// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/amazon": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "amazon"
                ],
                "summary": "Get the amazon product details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "amazon product url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_jobayer12_ScrapifyGo_utils.APIResponse-internal_scrape_amazon_Product"
                        }
                    }
                }
            }
        },
        "/api/v1/email": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "Get the email list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_jobayer12_ScrapifyGo_utils.APIResponse-array_string"
                        }
                    }
                }
            }
        },
        "/api/v1/sitemap": {
            "get": {
                "description": "Return sitemap url list. Example of the sitemap url: https://www.shopify.com/sitemap.xml",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sitemap"
                ],
                "summary": "Get the sitemap url list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_jobayer12_ScrapifyGo_utils.APIResponse-array_internal_scrape_sitemap_URL"
                        }
                    }
                }
            }
        },
        "/api/v1/url": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "url"
                ],
                "summary": "Get the url list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_jobayer12_ScrapifyGo_utils.APIResponse-array_string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_jobayer12_ScrapifyGo_utils.APIResponse-array_internal_scrape_sitemap_URL": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_scrape_sitemap.URL"
                    }
                },
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "github_com_jobayer12_ScrapifyGo_utils.APIResponse-array_string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "github_com_jobayer12_ScrapifyGo_utils.APIResponse-internal_scrape_amazon_Product": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_scrape_amazon.Product"
                },
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "internal_scrape_amazon.Product": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "price": {
                    "type": "string"
                },
                "rating": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "totalRating": {
                    "type": "string"
                }
            }
        },
        "internal_scrape_sitemap.URL": {
            "type": "object",
            "properties": {
                "changefreq": {
                    "type": "string"
                },
                "lastmod": {
                    "type": "string"
                },
                "loc": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Scrape API",
	Description:      "List of Scrape API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
